function plotSimuResult(plant, simuTimeStep, InitState, tau, x, p)
%plotSimuResult
%   Detailed explanation goes here
Dim = plant.Dim;
nStages = size(x, 2);
timeAxis = 0 : simuTimeStep : nStages * simuTimeStep;

% compute value of K
K = zeros(Dim.p, nStages);
for n = 1 : nStages
    K(:, n) = plant.computeVIFunc(tau(:, n), x(:, n), p(:, n));
end

%% plot
subplot(3,4,1)
plot(timeAxis, [InitState(1), x(1,:)],...
     timeAxis, [InitState(2), x(2,:)],...
     timeAxis, [InitState(3), x(3,:)],...
     timeAxis, [InitState(4), x(4,:)],...
     timeAxis, [InitState(5), x(5,:)],...
     timeAxis, [InitState(6), x(6,:)],...
     timeAxis, [InitState(7), x(7,:)],...
     timeAxis, [InitState(8), x(8,:)],...
     timeAxis, [InitState(9), x(9,:)],...
     timeAxis, [InitState(10), x(10,:)],...
     timeAxis, [InitState(11), x(11,:)],...     
     'LineWidth',1.2)
legend('x', 'z', 'torso', 'thigh1', 'calf1', 'thigh2', 'calf2', 'thigh3', 'calf3', 'thigh4', 'calf4')
xlabel('time(s)')
title('position')

subplot(3,4,2)
plot(timeAxis, [InitState(12), x(12,:)],...
     timeAxis, [InitState(13), x(13,:)],...
     timeAxis, [InitState(14), x(14,:)],...
     timeAxis, [InitState(15), x(15,:)],...
     timeAxis, [InitState(16), x(16,:)],...
     timeAxis, [InitState(17), x(17,:)],...
     timeAxis, [InitState(18), x(18,:)],...
     timeAxis, [InitState(19), x(19,:)],...
     timeAxis, [InitState(20), x(20,:)],...
     timeAxis, [InitState(21), x(21,:)],...
     timeAxis, [InitState(22), x(22,:)],...     
     'LineWidth',1.2)
legend('x', 'z', 'torso', 'thigh1', 'calf1', 'thigh2', 'calf2', 'thigh3', 'calf3', 'thigh4', 'calf4')
xlabel('time(s)')
title('velocity')

subplot(3,4,3)
plot(timeAxis(2:end), tau(1,:),...
    timeAxis(2:end), tau(2, :),...
    timeAxis(2:end), tau(3, :),...
    timeAxis(2:end), tau(4, :),...
    timeAxis(2:end), tau(5, :),...
    timeAxis(2:end), tau(6, :),...
    timeAxis(2:end), tau(7, :),...
    timeAxis(2:end), tau(8, :),...
    'LineWidth', 1.2)
legend('thigh1', 'calf1', 'thigh2', 'calf2', 'thigh3', 'calf3', 'thigh4', 'calf4')
xlabel('time(s)')
title('control')

subplot(3,4,5)
plot(timeAxis(2:end), p(1, :), 'k',...
     timeAxis(2:end), K(1, :), 'b','LineWidth', 1.2)
legend('force', 'gap') 
xlabel('time(s)')
title('normal contact force (leg 1)')

subplot(3,4,6)
plot(timeAxis(2:end), p(4, :), 'k',...
     timeAxis(2:end), K(4, :), 'b','LineWidth', 1.2)
legend('force', 'gap') 
xlabel('time(s)')
title('normal contact force (leg 2)')


subplot(3,4,7)
plot(timeAxis(2:end), p(7, :), 'k',...
     timeAxis(2:end), K(7, :), 'b','LineWidth', 1.2)
legend('force', 'gap') 
xlabel('time(s)')
title('normal contact force (leg 3)')

subplot(3,4,8)
plot(timeAxis(2:end), p(10, :), 'k',...
     timeAxis(2:end), K(10, :), 'b','LineWidth', 1.2)
legend('force', 'gap') 
xlabel('time(s)')
title('normal contact force (leg 4)')

subplot(3,4,9)
plot(timeAxis(2:end), tau(9, :), 'k',...
     timeAxis(2:end), (p(2, :) - p(3, :)), 'b',...
     'LineWidth', 1.2)
legend('force', 'velocity') 
xlabel('time(s)')
title('friction (leg 1)')

subplot(3,4,10)
plot(timeAxis(2:end), tau(10, :), 'k',...
     timeAxis(2:end), (p(5, :) - p(6, :)), 'b',...
     'LineWidth', 1.2)
legend('force', 'velocity') 
xlabel('time(s)')
title('friction (leg 2)')

subplot(3,4,11)
plot(timeAxis(2:end), tau(11, :), 'k',...
     timeAxis(2:end), (p(8, :) - p(9, :)), 'b',...
     'LineWidth', 1.2)
legend('force', 'velocity') 
xlabel('time(s)')
title('friction (leg 3)')

subplot(3,4,12)
plot(timeAxis(2:end), tau(12, :), 'k',...
     timeAxis(2:end), (p(11, :) - p(12, :)), 'b',...
     'LineWidth', 1.2)
legend('force', 'velocity') 
xlabel('time(s)')
title('friction (leg 4)')

end

