function K = autoGen_K(in1,in2,in3)
%AUTOGEN_K
%    K = AUTOGEN_K(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    27-Nov-2022 22:55:02

p1 = in3(1,:);
p4 = in3(4,:);
p7 = in3(7,:);
p10 = in3(10,:);
tau9 = in1(9,:);
tau10 = in1(10,:);
tau11 = in1(11,:);
tau12 = in1(12,:);
x2 = in2(2,:);
x3 = in2(3,:);
x4 = in2(4,:);
x5 = in2(5,:);
x6 = in2(6,:);
x7 = in2(7,:);
x8 = in2(8,:);
x9 = in2(9,:);
x10 = in2(10,:);
x11 = in2(11,:);
x24 = in2(24,:);
x28 = in2(28,:);
x32 = in2(32,:);
x36 = in2(36,:);
t2 = cos(x3);
t3 = p1./2.0;
t4 = p4./2.0;
t5 = p7./2.0;
t6 = p10./2.0;
t7 = t2.*(2.67e+2./1.0e+3);
t8 = -t7;
K = [x2-cos(x4)./5.0-cos(x5)./5.0;t3+tau9;t3-tau9;x2-cos(x6)./5.0-cos(x7)./5.0;t4+tau10;t4-tau10;t8+x2-cos(x8)./5.0-cos(x9)./5.0;t5+tau11;t5-tau11;t8+x2-cos(x10)./5.0-cos(x11)./5.0;t6+tau12;t6-tau12;x24;x24;x28;x28;x32;x32;x36;x36];
