clear all
clc

%%
Data_NIP = load('Data_time_step_NIP');
Data_IP = load('Data_time_step_IP');
%% plot
continuationStepNum = Data_NIP.rec.Info{1}.continuationStepNum;
s_sequence = Data_NIP.rec.Info{1}.Log.param(:, 1);
index = 0 : 1 : continuationStepNum;

figure(1)
semilogx(...
    s_sequence, Data_NIP.rec.Info{1}.Log.cost, 'g*',...
    s_sequence, Data_NIP.rec.Info{2}.Log.cost, 'b*',...
    s_sequence, Data_NIP.rec.Info{3}.Log.cost, 'k*',...
    s_sequence, Data_NIP.rec.Info{4}.Log.cost, 'r*',...
    s_sequence, Data_IP.rec.Info{1}.Log.cost, 'go',...
    s_sequence, Data_IP.rec.Info{2}.Log.cost, 'bo',...
    s_sequence, Data_IP.rec.Info{3}.Log.cost, 'ko',...
    s_sequence, Data_IP.rec.Info{4}.Log.cost, 'ro')
grid on

legend(Data_NIP.rec.name{1}, Data_NIP.rec.name{2}, Data_NIP.rec.name{3}, Data_NIP.rec.name{4},...
    Data_IP.rec.name{1}, Data_IP.rec.name{2}, Data_IP.rec.name{3}, Data_IP.rec.name{4},...
    'Interpreter','latex',...
    'Location','southwest',...
    'FontSize', 11)
xlabel('Relaxation parameter', 'FontSize', 11)
ylabel('Cost', 'FontSize', 11)
ylim([595, 622])
